name: pytorch-apex
channels:
  - conda-forge
dependencies:
  - filelock=3.13.1
  - fsspec=2024.2.0
  - jinja2=3.1.3
  - markupsafe=2.1.5
  - networkx=3.2.1
  - numpy=1.26.3
  - pip=25.0
  - python=3.11.7
  - sympy=1.12
  - typing-extensions=4.9.0
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/rocm6.0/
    - pytorch-triton-rocm==2.3.1
    - torch==2.3.1+rocm6.0
    - torchaudio==2.3.1+rocm6.0
    - torchvision==0.18.1+rocm6.0
    - jax[rocm]==0.4.35
    - jax-rocm60-pjrt==0.4.35
    - jax-rocm60-plugin==0.4.35
    - jaxlib==0.4.35
    - absl-py
    - cloudpickle
    - flatbuffers
    - hypothesis
    - mpmath>=1.3
    - pillow>=10.4.0
    - portpicker
    - pytest-xdist
    - rich
    - matplotlib
    - auditwheel