#!/bin/bash -e

#// This is a copy of the file provided by Samuel F Antao
#// Original License and code from https://github.com/sfantao/lumi-containers/tree/lumi-sep2024
#//
#//MIT License
#//
#//Copyright (c) 2023 Advanced Micro Devices, Inc.
#//
#//Permission is hereby granted, free of charge, to any person obtaining a copy
#//of this software and associated documentation files (the "Software"), to deal
#//in the Software without restriction, including without limitation the rights
#//to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#//copies of the Software, and to permit persons to whom the Software is
#//furnished to do so, subject to the following conditions:
#//
#//The above copyright notice and this permission notice shall be included in all
#//copies or substantial portions of the Software.
#//
#//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#//FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#//AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#//LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#//OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#//SOFTWARE.


bypass=0
if [[ "$@" == *" -c "* ]] ; then bypass=1 ; fi

if [ $bypass -eq 1 ] ; then 
    target=$(echo "$@" | grep -o '[^ ]*\.o')
    echo "bypassing default hipcc for $target"
    ROCM_PATH=$COMPILE_ROCM_PATH $COMPILE_ROCM_PATH/bin/hipcc $COMPILE_ROCM_PATH_EXTRA_FLAGS "$@"
    exit $?
fi

$ROCM_PATH/bin/hipcc.bak "$@"
exit $?
