name: pytorch-deepspeed
channels:
  - conda-forge
dependencies:
  - filelock=3.13.1
  - fsspec=2024.2.0
  - jinja2=3.1.3
  - markupsafe=2.1.5
  - mpmath=1.3.0
  - networkx=3.2.1
  - numpy=1.26.3
  - pillow=10.2.0
  - pip=25.0
  - python=3.11.7
  - sympy=1.12
  - typing-extensions=4.12.2
  - scipy
  - matplotlib
  - pandas
  - seaborn
  - transformers
  - protobuf
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/rocm6.0/
    - pytorch-triton-rocm==2.3.1
    - torch==2.3.1+rocm6.0
    - torchaudio==2.3.1+rocm6.0
    - torchvision==0.18.1+rocm6.0
    - deepspeed==0.14.0 --config-settings "--global-option=build_ext" --config-settings "--global-option=-j32"
    - sentencepiece==0.2.0
    - accelerate==1.3.0
