FROM registry.suse.com/bci/bci-base:15.5.36.14.13

#
# Disable BCI repros
#

RUN set -eux ; \
  sed -i 's#enabled=1#enabled=0#g' /etc/zypp/repos.d/SLE_BCI.repo

RUN set -eux ; \
  zypper -n addrepo http://download.opensuse.org/distribution/leap/15.5/repo/oss/ myrepo3 ; \
  echo 'gpgcheck=0' >> /etc/zypp/repos.d/myrepo3.repo ; \
  zypper -n addrepo https://download.opensuse.org/repositories/devel:/languages:/perl/SLE_15_SP5 myrepo4 ; \
  echo 'gpgcheck=0' >> /etc/zypp/repos.d/myrepo4.repo

RUN set -eux ; \
  sed -i 's#gpgcheck=1#gpgcheck=0#g' /etc/zypp/repos.d/*.repo

#
# Install build dependencies
#
RUN set -eux; \
  zypper -n refresh ; \
  zypper --no-gpg-checks -n install -y --force-resolution \
    git cmake gcc12 gcc12-c++ gcc12-fortran zlib-devel numactl awk patch tar autoconf automake libtool libjson-c-devel graphviz ncurses-devel nano which libjansson4 libnl3-200 wget; \
  zypper clean


ENV ROCM_RPM https://repo.radeon.com/amdgpu-install/6.2.4/sle/15.5/amdgpu-install-6.2.60204-1.noarch.rpm
ENV ROCM_RELEASE 6.2.4

COPY rocminfo rocm_agent_enumerator amdgpu-arch.cpp aws.patch /

RUN set -eux ; \
  zypper --no-gpg-checks -n install $ROCM_RPM

RUN set -eux ; \
  sed -i 's#gpgcheck=1#gpgcheck=0#g' /etc/zypp/repos.d/*.repo

RUN set -eux ; \
  zypper --no-gpg-checks -n install --oldpackage libsystemd0-249.16 libudev1-249.16

RUN set -eux ; \
  zypper refresh ; \
  amdgpu-install -y --no-dkms --usecase=rocm --rocmrelease=$ROCM_RELEASE ; \
  zypper cc -a

RUN set -eux ; \
  zypper --no-gpg-checks -n install -y --force miopen-hip-gfx90akdb

RUN set -eux ; \
  zypper --no-gpg-checks -n install -y --force omniperf omnitrace

#
# ROCm environment
#
ENV ROCM_PATH /opt/rocm-$ROCM_RELEASE
ENV PATH $ROCM_PATH/bin:$ROCM_PATH/llvm/bin:$PATH
ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:$ROCM_PATH/lib

#
# Mark RCCL as non-debug - this can me overriden by RCCL debug build.
#
ENV RCCL_DEBUG 0

RUN set -eux ; \
  cd $ROCM_PATH/bin ; \
  for i in rocm_agent_enumerator rocminfo ; do \
    rm -rf $i ; \
    cp /$i . ; \
    chmod +x $i ; \
  done

RUN set -eux ; \
  cd $ROCM_PATH/llvm/bin ; \
  rm amdgpu-arch offload-arch ; \
  g++-12 /amdgpu-arch.cpp -DNUM_TARGETS=8 -o amdgpu-arch ; \
  g++-12 /amdgpu-arch.cpp -DNUM_TARGETS=1 -o offload-arch ; \
  ./amdgpu-arch ; \
  ./offload-arch

ARG RCCL_VERSION=85eb1f1

RUN $WITH_CONDA ; set -eux ; \
  rm -rf /opt/mybuild ; \
  git clone https://github.com/rocm/rccl /opt/mybuild ; \
  cd /opt/mybuild ; \
  git checkout -b mydev $RCCL_VERSION ; \
  git submodule sync ; \
  git submodule update --init --recursive --jobs 0 ; \
  mkdir /opt/mybuild/build ; \
  cd  /opt/mybuild/build ; \
  CXX=$ROCM_PATH/bin/hipcc \
  cmake \
    -DBUILD_LOCAL_GPU_TARGET_ONLY=ON \
    -DCOMPILING_TARGETS=gfx90a \
    -DENABLE_MSCCLPP=OFF \
    -DCMAKE_INSTALL_PREFIX=/opt/rccl \
    -DCMAKE_BUILD_TYPE=Release \
    .. ; \
  nice make -j V=1 VERBOSE=1 ; \
  nice make -j install ; \
  cd / ; rm -rf /opt/mybuild

RUN set -eux ; \
  rm -rf $ROCM_PATH/lib/librccl.so* ; \
  ln -s /opt/rccl/lib/librccl.so* $ROCM_PATH/lib

RUN set -eux ; \
  cd $ROCM_PATH ; \
  find -iname '*.cmake' -o -iname '*.txt' | xargs grep -i librccl.so ; \
  find -iname '*.cmake' -o -iname '*.txt' | xargs sed -E -i 's#librccl.[0-9,a-z,\.]+#librccl.so.1.0#g' ; \
  find -iname '*.cmake' -o -iname '*.txt' | xargs grep -i librccl.so

# Latest libfabric build
ARG CASSINI_HEADERS_VERSION=9a8a738a879f007849fbc69be8e3487a4abf0952
ARG CXI_DRIVER_VERSION=c284516fa8d0027b8f84e8ca818e8c6bbe320bd8
ARG LIBCXI_VERSION=0f3609b5e224636abffc7ceffe6f4e9c83244c08

RUN set -eux; \
  zypper -n refresh ; \
  zypper --no-gpg-checks -n install -y --force-resolution \
    libconfig-devel \
    libuv-devel \
    fuse-devel  \
    libyaml-devel \
    libnl3-devel \
    libnuma-devel \
    libsensors4-devel \
    libcurl-devel \
    ; zypper clean

RUN set -eux ; \
  git clone --recursive https://github.com/HewlettPackard/shs-cassini-headers /opt/cassini-headers ; \
  git -C /opt/cassini-headers checkout -b mydev $CASSINI_HEADERS_VERSION ; \
  git clone --recursive https://github.com/HewlettPackard/shs-cxi-driver /opt/cxi-driver ; \
  git -C /opt/cxi-driver  checkout -b mydev $CXI_DRIVER_VERSION ; \
  git clone --recursive https://github.com/HewlettPackard/shs-libcxi /opt/shs-libcxi-src ; \
  git -C /opt/shs-libcxi-src checkout -b mydev $LIBCXI_VERSION ; \
  export CPATH=/opt/cassini-headers/include:/opt/cxi-driver/include ; \
  \
  cd /opt/shs-libcxi-src ; \
  ./autogen.sh ; \
  \
  cd /opt/shs-libcxi-src ; \
  CC=gcc-12 \
    CXX=g++-12 \
    CFLAGS='-Wno-unused-but-set-variable' \
      ./configure --prefix=/opt/shs-libcxi --with-rocm=$ROCM_PATH \
        --without-systemd \
        --with-systemdsystemunitdir=/opt/shs-libcxi/systemdsystemunitdir \
        --with-udevrulesdir=/opt/shs-libcxi/udevrulesdir ; \
  \
  sed -i "s#/usr/share/cassini-headers#/opt/cassini-headers/share/cassini-headers#g" /opt/shs-libcxi-src/utils/cxi_dump_csrs.py ; \
  \
  cd /opt/shs-libcxi-src ; \
  make VERBOSE=1 V=1 -j ; \
  make VERBOSE=1 V=1 -j install ; \
  \
  mv /opt/shs-libcxi-src/include /opt/shs-libcxi/include ; \
  cd / ; rm -rf /opt/shs-libcxi-src

ENV LD_LIBRARY_PATH=/opt/shs-libcxi/lib:$LD_LIBRARY_PATH
ENV LIBFABRIC_VERSION "e08d3161b8038ebfa50a4eb5bf76132e4eaeb137"

RUN set -eux ; \
  export CPATH=/opt/shs-libcxi/include:/opt/cassini-headers/include:/opt/cxi-driver/include ; \
  export LIBRARY_PATH=/opt/shs-libcxi/lib ; \
  \
  git clone --recursive https://github.com/ofiwg/libfabric /opt/libfabric-src ; \
  git -C /opt/libfabric-src checkout -b mydev $LIBFABRIC_VERSION ; \
  \
  cd /opt/libfabric-src ; \
  ./autogen.sh ; \
  \
  mkdir /opt/libfabric-src/build ; \
  \
  cd /opt/libfabric-src/build ; \
  ../configure CC=gcc-12 --prefix=/opt/libfabric \
    LDFLAGS=-Wl,--build-id --enable-only \
    --enable-restricted-dl --enable-tcp --enable-udp --enable-rxm --enable-rxd --enable-hook_debug \
    --enable-hook_hmem --enable-dmabuf_peer_mem --enable-cxi=/opt/shs-libcxi --enable-gdrcopy-dlopen --with-rocr=$ROCM_PATH ; \
  \
  cd /opt/libfabric-src/build ; \
  nice make V=1 VERBOSE=1 -j  ; \
  nice make V=1 VERBOSE=1 -j install ; \
  \
  cd / ; rm -rf /opt/libfabric-src

ENV LIBFABRIC_PATH=/opt/libfabric
ENV LD_LIBRARY_PATH=$LIBFABRIC_PATH/lib:$LD_LIBRARY_PATH


#ENV GCC_RELEASE=12

#ENV HWLOC_TAR=https://download.open-mpi.org/release/hwloc/v2.12/hwloc-2.12.2.tar.gz
#
#RUN set -eux ; \
#    cd / ;\
#    wget $HWLOC_TAR; \
#    tar -xzf hwloc-2.12.2.tar.gz ;\
#    cd hwloc-2.12.2 ;\
#    CC=gcc-$GCC_RELEASE ./configure --with-rocm=$ROCM_PATH --disable-rsmi --prefix=/opt/hwloc  --localstatedir=/var ;\
#    make install ;\
#    ldconfig

#ENV PATH=/opt/hwloc/bin:$PATH
#ENV LD_LIBRARY_PATH=/opt/hwloc/lib:$LD_LIBRARY_PATH

#ARG SLURM_VERSION=23-02-7-1
#RUN wget https://github.com/SchedMD/slurm/archive/slurm-${SLURM_VERSION}.tar.gz \
# && tar -xf slurm-${SLURM_VERSION}.tar.gz \
# && cd slurm-slurm-${SLURM_VERSION} \
# && ./configure --prefix=/opt/slurm \
# && cd contribs/pmi2 \
# && make -j$(getconf _NPROCESSORS_ONLN) install \
# && rm -Rf ../../../slurm*
#ENV LD_LIBRARY_PATH=/opt/slurm/lib:$LD_LIBRARY_PATH
#ENV LD_RUN_PATH=/opt/slurm/lib:$LD_RUN_PATH

# Channel 4 only works on v >= 3.4.3
ENV MPICH_VERSION=4.2.3
ENV MPICH_PATH=/opt/mpich
ENV MPICH_TAR=http://www.mpich.org/static/downloads/${MPICH_VERSION}/mpich-${MPICH_VERSION}.tar.gz

#
# Add MPICH
RUN set -eux ; \
    cd / ;\
    curl -LO $MPICH_TAR ; \
    tar -xzf mpich-$MPICH_VERSION.tar.gz; \
    rm mpich-$MPICH_VERSION.tar.gz;\
    cd mpich-$MPICH_VERSION ;\
    CC=gcc-12 CXX=g++-12  \
        ./configure --prefix=$MPICH_PATH  \
            --with-hip-lib=$ROCM_PATH/lib/  \
            --with-hip-include=$ROCM_PATH/include/  \
            --with-libfabric=/opt/libfabric  \
            --disable-fortran \
            --enable-fast=all,O3  \
#            --disable-fast \
            --with-device=ch4:ofi:cxi \
#            --with-pmi=pmi2 \
#            --with-pmi-include==/opt/slurm/include/slurm/ \
#            --with-pmi-lib==/opt/slurm/lib/ \
#            --with-pmilib=install \
            --with-pm=no \
            --disable-silent-rules \
            --enable-debuginfo \
#            --with-hwloc=/opt/hwloc \
            --enable-shared ;\
    make -j 12;\
    make install;\
    ldconfig

ARG AWS_PLUGIN_VERSION=17d41cb

RUN set -eux ; \
  git clone -b cxi https://github.com/rocm/aws-ofi-rccl /opt/mybuild ; \
  cd /opt/mybuild ; \
  git checkout -b mydev $AWS_PLUGIN_VERSION ; \
  git apply < /aws.patch ; \
  ./autogen.sh ; \
  \
  cd /opt/mybuild ; \
  export CPATH=$LIBFABRIC_PATH/include ; \
  export LIBRARY_PATH=$LD_LIBRARY_PATH ; \
  LDFLAGS='-L/opt/shs-libcxi/lib -lcxi' CC=gcc-12 ./configure --with-libfabric=$LIBFABRIC_PATH --enable-trace --with-hip=$ROCM_PATH --with-rccl=$ROCM_PATH --disable-tests ; \
  LDFLAGS='-L/opt/shs-libcxi/lib -lcxi' CC=gcc-12 nice make -j ; \
  mkdir /opt/aws-ofi-rccl ; \
  mv src/.libs/librccl-net.so* /opt/aws-ofi-rccl ; \
  rm -rf /opt/mybuild


#
# Add relevant libs to execution environment
#
ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:/opt/aws-ofi-rccl


#
# Install miniconda
#
RUN set -eux ; \
  curl -LO https://repo.anaconda.com/miniconda/Miniconda3-py312_24.5.0-0-Linux-x86_64.sh ; \
  bash ./Miniconda3-* -b -p /opt/miniconda3 -s ; \
  rm -rf ./Miniconda3-*

ENV WITH_CONDA "source /opt/miniconda3/bin/activate base"
#
# Install conda environment
#
ARG PYTHON_VERSION=3.12.0
RUN $WITH_CONDA; set -eux ; \
  conda create -n pytorch python=$PYTHON_VERSION ; \
  conda activate pytorch ; \
  conda install -y ninja pillow cmake pyyaml
ENV WITH_CONDA "source /opt/miniconda3/bin/activate pytorch"

# Repository for the wheel files
RUN set -eux ; \
  mkdir /opt/wheels

#
# Install pytorch
#

# PyTorch comes with RCCL from ROCm 6.0.0 which cause a segmentation fault
# in the tests. It's supspected it's related to https://github.com/ROCm/rccl/pull/1153
# Copying the RCCL library from /opt/rocm, solve the issue.

ENV PYTORCH_ROCM_ARCH gfx90a
ENV PYTORCH_VERSION="2.7.1+rocm6.2.4"
ARG PYTORCH_DEBUG
ARG PYTORCH_RELWITHDEBINFO
ENV TORCHVISION_VERSION="0.22.1+rocm6.2.4"

RUN $WITH_CONDA; set -eux ; \
  pip3 install --pre torch==${PYTORCH_VERSION} --index-url https://download.pytorch.org/whl/rocm6.2.4/ ; \
  cp /opt/rocm/lib/librccl.so $(dirname $(python -c 'import torch; print(torch.__file__)'))/lib

#
# Pytorch dependencies
#
RUN $WITH_CONDA; set -eux ; \
  pip install packaging

#ARG APEX_VERSION
#RUN $WITH_CONDA; set -eux ; \
#  git clone --recursive https://github.com/rocm/apex /opt/mybuild ; \
#  cd /opt/mybuild ; \
#  git checkout -b mydev $APEX_VERSION ; \
#  git submodule sync ; \
#  git submodule update --init --recursive --jobs 0 ; \
#  CC=gcc-12, CXX=g++-12 nice python setup.py bdist_wheel --cpp_ext --cuda_ext ; \
#  cp -rf dist/* /opt/wheels ; \
#  rm -rf /opt/mybuild

#RUN $WITH_CONDA; set -eux ; \
#  pip install /opt/wheels/apex-*.whl

RUN $WITH_CONDA; set -eux ; \
  pip3 install --pre torchvision==$TORCHVISION_VERSION --index-url https://download.pytorch.org/whl/

#
# AMD-SMI
#
RUN $WITH_CONDA; set -eux ; \
  cd $ROCM_PATH/share/amd_smi ; \
  python3 -m pip wheel . --wheel-dir=/opt/wheels ; \
  pip install /opt/wheels/amdsmi-*.whl

#ARG TORCHDATA_VERSION
#RUN $WITH_CONDA; set -eux ; \
#  pip3 install --pre torchdata==$TORCHDATA_VERSION --index-url https://download.pytorch.org/whl/
#
#ARG TORCHTEXT_VERSION
#RUN $WITH_CONDA; set -eux ; \
#  pip3 install --pre torchtext==$TORCHTEXT_VERSION --index-url https://download.pytorch.org/whl/

ARG TORCHAUDIO_VERSION="2.7.1+rocm6.2.4"
RUN $WITH_CONDA; set -eux ; \
  pip3 install --pre torchaudio==${TORCHAUDIO_VERSION} --index-url https://download.pytorch.org/whl/

#
# Deepspeed
#
ENV RUSTUP_HOME /opt/rust
ENV CARGO_HOME /opt/rust
RUN set -eux ; \
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > /opt/rust.sh ; \
  sh /opt/rust.sh -y --no-modify-path ; \
  rm -rf /opt/rust.sh

ENV PATH $PATH:/opt/rust/bin

RUN $WITH_CONDA; set -eux ; \
  conda install -y  -c conda-forge oneccl-devel

#RUN $WITH_CONDA; set -eux ; \
#  ln -s $(which gcc-12) /opt/rust/bin/cc ; \
#  CC=gcc-12 CXX=g++-12 \
#  DS_BUILD_AIO=0 \
#  DS_BUILD_CCL_COMM=1 \
#  DS_BUILD_CPU_ADAM=1 \
#  DS_BUILD_CPU_LION=1 \
#  DS_BUILD_EVOFORMER_ATTN=0 \
#  DS_BUILD_FUSED_ADAM=1 \
#  DS_BUILD_FUSED_LION=1 \
#  DS_BUILD_CPU_ADAGRAD=0 \
#  DS_BUILD_FUSED_LAMB=1 \
#  DS_BUILD_QUANTIZER=0 \
#  DS_BUILD_RANDOM_LTD=0 \
#  DS_BUILD_SPARSE_ATTN=0 \
#  DS_BUILD_TRANSFORMER=0 \
#  DS_BUILD_TRANSFORMER_INFERENCE=0 \
#  DS_BUILD_STOCHASTIC_TRANSFORMER=1 \
#  DS_ACCELERATOR=cuda \
#  pip install deepspeed==0.15.1 --global-option="build_ext" --global-option="-j32" ; \
#  ds_report ; \
#  true

#
# flash-attention
#
#RUN $WITH_CONDA; set -eux ; \
#  git clone -b v2.7.3 --recursive https://github.com/Dao-AILab/flash-attention /opt/mybuild ; \
#  cd /opt/mybuild ; \
#  cp -rf benchmarks /opt/wheels/flash_attn-benchmarks ; \
#  \
#  rm -rf build ; \
#  MAX_JOBS=32 \
#  CC=gcc-12 \
#  CXX=g++-12 \
#  GPU_ARCHS="gfx90a" \
#    python setup.py bdist_wheel ; \
#  cp -rf dist/* /opt/wheels ; \
#  \
#  rm -rf /opt/mybuild
#
#RUN $WITH_CONDA; set -eux ; \
#  pip install /opt/wheels/flash_attn-*.whl

#
# xformers - tested with 06b548c
#
RUN $WITH_CONDA; set -eux ; \
  git clone --recursive -b develop https://github.com/ROCm/xformers /opt/mybuild ; \
  cd /opt/mybuild ; \
  \
  rm -rf build ; \
  CC=gcc-12 \
  CXX=g++-12 \
  HIP_ARCHITECTURES="gfx90a" \
  PYTORCH_ROCM_ARCH="gfx90a" \
  python setup.py bdist_wheel ; \
  cp -rf dist/* /opt/wheels ; \
  \
  rm -rf /opt/mybuild

RUN $WITH_CONDA; set -eux ; \
  pip install /opt/wheels/xformers-*.whl

RUN $WITH_CONDA; set -eux ; \
  pip install \
    scipy==1.12.0 \
    matplotlib==3.8.2 \
    pandas==2.2.0 \
    seaborn==0.13.2

#
# Bits and bytes - tested with 35266ea (was e4fe8b5)
#
RUN $WITH_CONDA; set -eux ; \
  git clone https://github.com/ROCm/bitsandbytes /opt/mybuild ; \
  cd /opt/mybuild ; \
  git checkout -b mydev 35266ea ; \
  pip install -r requirements-dev.txt ; \
  cmake -DCOMPUTE_BACKEND=hip -DBNB_ROCM_ARCH="gfx90a" -S . ; \
  nice make -j ; \
  python setup.py bdist_wheel ; \
  cp dist/bitsandbytes-*.whl /opt/wheels ; \
  \
  cd / ; \
  rm -rf /opt/mybuild ; \
  true

RUN $WITH_CONDA; set -eux ; \
  pip install /opt/wheels/bitsandbytes-*.whl

#
# Some other packages we may need
#
RUN $WITH_CONDA; set -eux ; \
  pip install \
    'numpy<2' \
    transformers==4.46.3 \
    sentencepiece==0.2.0 \
    protobuf==5.27.1 \
    accelerate==0.34.2 \
    tensorboard==2.18.0 \
    openpyxl==3.1.5

#
# VLLM
#
#RUN #$WITH_CONDA; set -eux ; \
##  pip install \
##    setuptools_scm

#ARG VLLM_VERSION
#RUN $WITH_CONDA ; set -eux ; \
#  git clone --recursive -b $VLLM_VERSION https://github.com/rocm/vllm /opt/mybuild ; \
#  \
#  cd /opt/mybuild ; \
#  CC=gcc-12 \
#    CXX=g++-12 \
#    python3 setup.py bdist_wheel --dist-dir=/opt/wheels ; \
#  \
#  rm -rf /opt/mybuild

#RUN $WITH_CONDA; set -eux ; \
#  pip install \
#    /opt/wheels/vllm-*.whl

#
# Transformer engine - tested e7a7f6d
#
RUN $WITH_CONDA; set -eux ; \
  export NVTE_FRAMEWORK=pytorch ; \
  export NVTE_ROCM_ARCH=gfx90a ; \
  rm -rf /opt/mybuild ; \
  git clone --recursive https://github.com/ROCm/TransformerEngine.git /opt/mybuild ; \
  cd /opt/mybuild ; \
  git checkout -b mydev df12b25 ; \
  git submodule sync ; \
  git submodule update --init --recursive --jobs 0 ; \
  sed -i 's/-Werror//g' /opt/mybuild/3rdparty/aotriton/third_party/triton/CMakeLists.txt ; \
  CC=clang \
    CXX=clang++ \
    CFLAGS='-Wno-error -Wno-c++11-narrowing' \
    CXXFLAGS='-Wno-error -Wno-c++11-narrowing' \
    TORCH_DONT_CHECK_COMPILER_ABI=1 \
    pip wheel --no-deps --verbose -e . -w /opt/wheels ; \
  rm -rf /opt/mybuild

RUN $WITH_CONDA; set -eux ; \
  pip install \
    /opt/wheels/transformer_engine-*.whl

# force all RCCL streams to be high priority
ENV TORCH_NCCL_HIGH_PRIORITY 1
ENV RCCL_MSCCL_ENABLE 0

RUN $WITH_CONDA; set -eux ; \
  CC=gcc-12 \
  CXX=g++-12 \
  pip3 install \
    scipy \
    einops \
    flask-restful \
    nltk \
    pytest \
    pytest-cov \
    pytest_mock \
    pytest-csv \
    pytest-random-order \
    sentencepiece \
    wrapt \
    zarr \
    wandb \
    tensorstore==0.1.45 \
    pytest_mock \
    pybind11 \
    setuptools \
    datasets \
    tiktoken \
    pynvml

RUN $WITH_CONDA; set -eux ; \
  pip3 install "huggingface_hub[cli]"

# Is this needed?
# RUN $WITH_CONDA; set -eux ; \
#   python3 -m nltk.downloader punkt_tab

ENV CAUSAL_CONV1D_FORCE_BUILD=TRUE
ENV MAMBA_FORCE_BUILD=TRUE
ENV HIP_ARCHITECTURES=gfx90a

RUN $WITH_CONDA; set -eux ; \
  rm -rf /opt/mybuild ;\
  git clone https://github.com/Dao-AILab/causal-conv1d /opt/mybuild ; \
  cd /opt/mybuild ; \
  CC=gcc-12 \
  CXX=g++-12 \
    python3 setup.py bdist_wheel --dist-dir=/opt/wheels ; \
  cd / ; rm -rf /opt/mybuild

RUN $WITH_CONDA; set -eux ; \
  rm -rf /opt/mybuild ;\
  git clone https://github.com/state-spaces/mamba /opt/mybuild ; \
  cd /opt/mybuild ; \
  CC=gcc-12 \
  CXX=g++-12 \
    python3 setup.py bdist_wheel --dist-dir=/opt/wheels ; \
  cd / ; rm -rf /opt/mybuild

# For transformer engine.
ENV NVTE_USE_HIPBLASLT=1

RUN $WITH_CONDA; set -eux ; \
  rm -rf /opt/mybuild ;\
  git clone https://github.com/caaatch22/grouped_gemm.git /opt/mybuild ; \
  cd /opt/mybuild ; \
  git checkout rocm ; \
  git submodule sync ; \
  git submodule update --init --recursive --jobs 0 ; \
  CC=gcc-12 \
  CXX=g++-12 \
    python3 setup.py bdist_wheel --dist-dir=/opt/wheels ; \
  cd / ; rm -rf /opt/mybuild

RUN $WITH_CONDA; set -eux ; \
  pip install /opt/wheels/causal_conv1d-*.whl ; \
  true

#ARG TRITON_VERSION
#RUN $WITH_CONDA; set -eux ; \
#  git clone --recursive https://github.com/triton-lang/triton /opt/mybuild ; \
#  cd /opt/mybuild ; \
#  git checkout -b mydev $TRITON_VERSION ; \
#  git submodule sync ; \
#  git submodule update --init --recursive --jobs 0 ; \
#  CC=gcc-12 \
#    CXX=g++-12 \
#    pip wheel --no-deps -e python -w /opt/wheels ; \
#    cd / ; rm -rf /opt/mybuild

#RUN #$WITH_CONDA; set -eux ; \
##    pip install /opt/wheels/triton-*.whl ; \
##    true

RUN $WITH_CONDA; set -eux ; \
  pip install /opt/wheels/mamba_ssm-*.whl ; \
  true

RUN $WITH_CONDA; set -eux ; \
  pip install /opt/wheels/grouped_gemm-*.whl ; \
  true

#ARG MEGATRON_VERSION
#RUN $WITH_CONDA; set -eux ; \
#  rm -rf /opt/mybuild ;\
#  git clone https://github.com/ROCm/Megatron-LM.git /opt/mybuild ; \
#  cd /opt/mybuild ; \
#  git checkout -b mydev $MEGATRON_VERSION ; \
#  git submodule sync ; \
#  git submodule update --init --recursive --jobs 0 ; \
#  CC=gcc-12 \
#  CXX=g++-12 \
#    python3 setup.py bdist_wheel --dist-dir=/opt/wheels ; \
#  cd / ; rm -rf /opt/mybuild

#RUN $WITH_CONDA; set -eux ; \
#  pip install /opt/wheels/megatron_core-*.whl ; \
#  true

# Use container libstdc++.so
RUN $WITH_CONDA; set -eux ; \
  rm $CONDA_PREFIX/lib/libstdc++.*
RUN $WITH_CONDA; set -eux ; \
  cd $(dirname $(python -c "import torch; print(torch.__file__)"))/lib ; \
  for i in * ; do if [ -f /opt/rocm/lib/$i ] ; then rm $i ; fi ; done ; \
  for i in * ; do if [ -d /opt/rocm/lib/$i ] ; then rm -rf $i ; fi ; done

RUN $WITH_CONDA; set -eux ; \
  cd $(dirname $(python -c "import torch; print(torch.__file__)"))/lib ; \
  for i in * ; do if [ -f /opt/amdgpu/lib64/$i ] ; then rm $i ; fi ; done
ENV NCCL_SOCKET_IFNAME='hsn0,hsn1,hsn2,hsn3'
ENV NCCL_NET_GDR_LEVEL=PHB

#
# Check https://support.hpe.com/hpesc/public/docDisplay?docId=dp00004854en_us&docLocale=en_US for details
#
# ENV FI_MR_CACHE_MONITOR=userfaultfd
# ENV FI_CXI_DEFAULT_CQ_SIZE=131072
# ENV FI_CXI_RX_MATCH_MODE=software
# ENV FI_CXI_RDZV_PROTO=alt_read
# # Increase for larger jobs
# ENV FI_CXI_REQ_BUF_SIZE=256
ARG TORCHAO_VERSION=0.9.0+rocm6.2.4
RUN $WITH_CONDA; set -eux ; \
  pip3 install --pre torchao==$TORCHAO_VERSION --index-url https://download.pytorch.org/whl/

ARG TORCHTUNE_VERSION=v0.6.0
RUN $WITH_CONDA; set -eux ; \
  git clone -b $TORCHTUNE_VERSION --recursive https://github.com/pytorch/torchtune /opt/mybuild ; \
  cd /opt/mybuild ; \
  pip wheel --no-deps -e . -w /opt/wheels ; \
  pip install /opt/wheels/torchtune-*.whl ; \
  cd / ; rm -rf /opt/mybuild

RUN $WITH_CONDA; set -eux ; \
  CC=gcc-12 \
  CXX=g++-12 \
  pip install \
    beautifulsoup4==4.13.3 \
    lightning==2.5.1 \
    evaluate==0.4.3 \
    fasttext==0.9.3 \
    scikit-learn==1.6.1 \
    scikit-image==0.25.2 \
    gensim==4.3.3 \
    gradio==5.23.1 \
    lighteval==0.8.1 \
    numba==0.61.0 \
    pyrsmi==0.2.0 \
    pysqlite3==0.5.4 \
    sentence-transformers==3.4.1 \
    tensorboardX==2.6.2.2 \
    torch-tb-profiler==0.4.3 \
    tornado==6.4.2 \
    tqdm-multiprocess==0.0.11 \
    zstandard==0.23.0
ENV CONDA_DEFAULT_ENV=pytorch
ENV CONDA_SHLVL=1
ENV CONDA_EXE="/opt/miniconda3/bin/conda"
ENV CONDA_PREFIX="/opt/miniconda3/envs/$CONDA_DEFAULT_ENV"
ENV _CE_M=''
ENV CONDA_PYTHON_EXE="/opt/miniconda3/bin/python"
ENV _CE_CONDA=''
ENV CONDA_PROMPT_MODIFIER="($CONDA_DEFAULT_ENV)"
ENV PATH="/opt/miniconda3/envs/$CONDA_DEFAULT_ENV/bin:/opt/miniconda3/condabin:$PATH"

# Disable the WITH_CONDA helper
ENV WITH_CONDA=true
