
#// This is a heavily modified version of a file provided by Samuel F Antao
#// Original License and code from https://github.com/sfantao/lumi-containers/tree/lumi-sep2024
#//
#//MIT License
#//
#//Copyright (c) 2023 Advanced Micro Devices, Inc.
#//
#//Permission is hereby granted, free of charge, to any person obtaining a copy
#//of this software and associated documentation files (the "Software"), to deal
#//in the Software without restriction, including without limitation the rights
#//to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#//copies of the Software, and to permit persons to whom the Software is
#//furnished to do so, subject to the following conditions:
#//
#//The above copyright notice and this permission notice shall be included in all
#//copies or substantial portions of the Software.
#//
#//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#//FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#//AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#//LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#//OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#//SOFTWARE.


# update & upgrade image and install some base packages
RUN zypper refresh
RUN zypper update -y
RUN set -eux ; \
  zypper --no-gpg-checks -n install -y --force-resolution \
    git cmake gcc${GCC_RELEASE} gcc${GCC_RELEASE}-c++ gcc${GCC_RELEASE}-fortran zlib-devel numactl awk patch tar autoconf automake libtool libjson-c-devel graphviz ncurses-devel nano which perl wget lbzip2  libjansson4 libnl3-200; \
  zypper clean

