
# --> latest commit on main
RUN set -eux ; \
    cd /opt/ ;\
    git clone https://github.com/HewlettPackard/shs-cassini-headers;\
    git -C /opt/shs-cassini-headers checkout -b mydev $CASSINI_HEADERS_VERSION ; \
    mkdir -p /share/cassini-headers/;\
    mkdir -p /include;\
    cp shs-cassini-headers/share/cassini-headers/csr_defs.json /share/cassini-headers/;\
    cp -r shs-cassini-headers/include/* /include/

# --> latest commit on main
RUN set -eux ; \
    cd /opt/ ;\
    git clone https://github.com/HewlettPackard/shs-cxi-driver ;\
    git -C /opt/shs-cxi-driver  checkout -b mydev $CXI_DRIVER_VERSION ; \
    cp -r shs-cxi-driver/include/* /include/

#0f3609b5e224636abffc7ceffe6f4e9c83244c08 --> latest commit on main
RUN set -eux ; \
    export CPATH=/include ; \
    cd /opt/ ;\
    git clone http://github.com/HewlettPackard/shs-libcxi ;\
    git -C /opt/shs-libcxi checkout -b mydev $LIBCXI_VERSION ; \
    cd shs-libcxi; \
#    git checkout 0f3609b5e224636abffc7ceffe6f4e9c83244c08;\
    sed -i 's+/usr/share/cassini-headers/csr_defs.json+/share/cassini-headers/csr_defs.json+g' utils/cxi_dump_csrs.py ;\
    ./autogen.sh;\
    CC=gcc-$GCC_RELEASE CXX=g++-$GCC_RELEASE CFLAGS='-Wno-unused-but-set-variable' \
      ./configure --prefix=$LIBCXI_PATH --with-rocm=$ROCM_PATH \
        --without-systemd \
        --with-systemdsystemunitdir=/opt/shs-libcxi/systemdsystemunitdir \
        --with-udevrulesdir=/opt/shs-libcxi/udevrulesdir ; \
    make VERBOSE=1 V=1 -j ; \
    make VERBOSE=1 V=1 -j install

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LIBCXI_PATH/lib
ENV LD_RUN_PATH=$LD_RUN_PATH:$LIBCXI_PATH/lib
