
# need version higher than 1.15.2. 1.15 does not have a cxi provider
# sed is needed to delete the CXI_MAP_IOVA_ALLOC as it was removed. https://github.com/search?q=repo%3AHewlettPackard%2Fshs-libcxi+CXI_MAP_IOVA_ALLOC&type=commits

### LIBFABRIC from releases
RUN set -eux ; \
    wget https://github.com/ofiwg/libfabric/releases/download/v$LIBFABRIC_VERSION/libfabric-$LIBFABRIC_VERSION.tar.bz2 ; \
    tar -xf libfabric-$LIBFABRIC_VERSION.tar.bz2; \
    rm libfabric-$LIBFABRIC_VERSION.tar.bz2; \
    cd libfabric-$LIBFABRIC_VERSION; \
    sed -i 's/| CXI_MAP_IOVA_ALLOC//g' prov/cxi/include/cxip.h ;\
    configure CC=gcc-$GCC_RELEASE --prefix=$LIBFABRIC_PATH \
        LDFLAGS=-Wl,--build-id --enable-only \
        --enable-restricted-dl --enable-tcp --enable-udp --enable-rxm --enable-rxd --enable-hook_debug \
        --enable-hook_hmem --enable-dmabuf_peer_mem --enable-cxi=$LIBCXI_PATH --enable-gdrcopy-dlopen --with-rocr=$ROCM_PATH ; \
    make -j;\
    make install;\
    ldconfig ;\
    cd /; \
    rm -rf libfabric-$LIBFABRIC_VERSION

ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:$LIBFABRIC_PATH/lib
ENV LD_RUN_PATH $LD_RUN_PATH:$LIBFABRIC_PATH/lib
